import React from 'react';
import { Link } from 'react-router-dom';
import { Brain, Zap, Target, Award, ArrowRight } from 'lucide-react';
import './Home.css';

function Home() {
  const features = [
    {
      icon: <Brain className="feature-icon" />,
      title: "AI-Powered Questions",
      description: "Get personalized quiz questions generated by advanced AI technology"
    },
    {
      icon: <Zap className="feature-icon" />,
      title: "Multiple Subjects",
      description: "Choose from various subjects including Math, Science, History, and more"
    },
    {
      icon: <Target className="feature-icon" />,
      title: "Adaptive Difficulty",
      description: "Questions adapt to your skill level for optimal learning experience"
    },
    {
      icon: <Award className="feature-icon" />,
      title: "Instant Results",
      description: "Get immediate feedback and detailed explanations for each answer"
    }
  ];

  return (
    <div className="home">
      <div className="container">
        {/* Hero Section */}
        <section className="hero">
          <div className="hero-content">
            <h1 className="hero-title">
              Master Any Subject with
              <span className="gradient-text"> AI-Powered Quizzes</span>
            </h1>
            <p className="hero-description">
              Challenge yourself with personalized quizzes generated by advanced AI. 
              Learn, practice, and excel in your favorite subjects with instant feedback 
              and adaptive difficulty levels.
            </p>
            <div className="hero-actions">
              <Link to="/quiz-selection" className="btn btn-primary btn-large">
                Start Learning
                <ArrowRight size={20} />
              </Link>
              <button className="btn btn-outline btn-large">
                Learn More
              </button>
            </div>
          </div>
          <div className="hero-visual">
            <div className="floating-card card-1">
              <Brain size={32} />
              <span>Mathematics</span>
            </div>
            <div className="floating-card card-2">
              <Zap size={32} />
              <span>Science</span>
            </div>
            <div className="floating-card card-3">
              <Target size={32} />
              <span>History</span>
            </div>
            <div className="floating-card card-4">
              <Award size={32} />
              <span>Literature</span>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section className="features">
          <div className="section-header">
            <h2 className="section-title">Why Choose Our Quiz Portal?</h2>
            <p className="section-description">
              Experience the future of learning with our AI-powered quiz platform
            </p>
          </div>
          <div className="features-grid">
            {features.map((feature, index) => (
              <div key={index} className="feature-card">
                <div className="feature-icon-wrapper">
                  {feature.icon}
                </div>
                <h3 className="feature-title">{feature.title}</h3>
                <p className="feature-description">{feature.description}</p>
              </div>
            ))}
          </div>
        </section>

        {/* CTA Section */}
        <section className="cta">
          <div className="cta-content">
            <h2 className="cta-title">Ready to Test Your Knowledge?</h2>
            <p className="cta-description">
              Join thousands of students who are already improving their skills with our AI-powered quizzes
            </p>
            <Link to="/quiz-selection" className="btn btn-primary btn-large">
              Get Started Now
              <ArrowRight size={20} />
            </Link>
          </div>
        </section>
      </div>
    </div>
  );
}

export default Home;
